// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SqlConsoleApp.SqlContext.Models
{
    public partial class GetEmployeInfo
    {
        public string PeopleName { get; }
        public string PeopleSurname { get; }
        public string Gid { get; }
        public string Mail { get; }
        public string Telephone { get; }
        public string NameShortPhone { get; }
        public string Organisation { get; }
        public string Scdcompany { get; }
        public bool? IsExtern { get; }
        public bool? IsHead { get; }
        public int? IdMitarbeiter { get; }
        public int? IdOrganisation { get; }
        public double? OverHours { get; }
        public int? AbsenceDays { get; }
        public int? MissingPresenceDays { get; }
        public double? WeeklyWorkingHours { get; }
        public int? AvailableVacationDays { get; }
        public int? PlannedVacationDays { get; }
        public int? VacationDays { get; }
        public int? ShortTimeDays { get; }
        public int? SicknessDays { get; }
    }
}