// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SqlConsoleApp.SqlContext.Models
{
    public partial class GetPresenceAbscenceOverview
    {
        public int? Year { get; }
        public int? Month { get; }
        public string MonthName { get; }
        public int? Week { get; }
        public DateTime? Date { get; }
        public string DayName { get; }
        public string DayType { get; }
        public TimeSpan? StartTime { get; }
        public TimeSpan? EndTime { get; }
        public double? WorkingHours { get; }
        public double? OverHours { get; }
        public int? IdCalendarTable { get; }
        public int? IdMitarbeiter { get; }
        public int? IdOrganisation { get; }
    }
}