//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ValidationXSDXML.List
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    [System.Xml.Serialization.XmlRootAttribute("Data", Namespace = "http://devices.wkc.siemens.de/MCP", IsNullable = false)]
    public partial class DataType
    {

        private System.Collections.Generic.List<DeviceType> devicesField;

        private System.Collections.Generic.List<PanelType> panelsField;

        private System.Collections.Generic.List<BoardType> boardsField;

        private System.Collections.Generic.List<ConnectorType> connectorsField;

        private System.Collections.Generic.List<ModuleType> modulesField;

        private System.Collections.Generic.List<SwitchType> switchesField;

        private System.Collections.Generic.List<LabelType> labelsField;

        private System.Collections.Generic.List<HardwareIdentType> hardwareIdentsField;

        private System.Collections.Generic.List<FirmwareType> firmwareFilesField;

        private System.Collections.Generic.List<AttributeFileType> attributeFilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Device", IsNullable = false)]
        public System.Collections.Generic.List<DeviceType> Devices
        {
            get
            {
                return this.devicesField;
            }
            set
            {
                this.devicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Panel", IsNullable = false)]
        public System.Collections.Generic.List<PanelType> Panels
        {
            get
            {
                return this.panelsField;
            }
            set
            {
                this.panelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Board", IsNullable = false)]
        public System.Collections.Generic.List<BoardType> Boards
        {
            get
            {
                return this.boardsField;
            }
            set
            {
                this.boardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Connector", IsNullable = false)]
        public System.Collections.Generic.List<ConnectorType> Connectors
        {
            get
            {
                return this.connectorsField;
            }
            set
            {
                this.connectorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Module", IsNullable = false)]
        public System.Collections.Generic.List<ModuleType> Modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Switch", IsNullable = false)]
        public System.Collections.Generic.List<SwitchType> Switches
        {
            get
            {
                return this.switchesField;
            }
            set
            {
                this.switchesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Label", IsNullable = false)]
        public System.Collections.Generic.List<LabelType> Labels
        {
            get
            {
                return this.labelsField;
            }
            set
            {
                this.labelsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HardwareIdent", IsNullable = false)]
        public System.Collections.Generic.List<HardwareIdentType> HardwareIdents
        {
            get
            {
                return this.hardwareIdentsField;
            }
            set
            {
                this.hardwareIdentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Firmware", IsNullable = false)]
        public System.Collections.Generic.List<FirmwareType> FirmwareFiles
        {
            get
            {
                return this.firmwareFilesField;
            }
            set
            {
                this.firmwareFilesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeFile", IsNullable = false)]
        public System.Collections.Generic.List<AttributeFileType> AttributeFiles
        {
            get
            {
                return this.attributeFilesField;
            }
            set
            {
                this.attributeFilesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class DeviceType : PartType
    {

        private string mLFBField;

        private string internalNameField;

        private string functionalStateField;

        private string hardwareIdentIDField;

        private string firmwareIDField;

        private System.Collections.Generic.List<AttributeFileAssignType> attributeFilesField;

        private System.Collections.Generic.List<byte> macAddressesField;

        private string inputImageByteCountField;

        private string outputImageByteCountField;

        private string panelIDField;

        private System.Collections.Generic.List<BoardMountType> boardsField;

        private System.Collections.Generic.List<ModuleMountType> modulesField;

        private System.Collections.Generic.List<ConnectorMountType> connectorsField;

        private System.Collections.Generic.List<WireType> wiringField;

        /// <remarks/>
        public string MLFB
        {
            get
            {
                return this.mLFBField;
            }
            set
            {
                this.mLFBField = value;
            }
        }

        /// <remarks/>
        public string InternalName
        {
            get
            {
                return this.internalNameField;
            }
            set
            {
                this.internalNameField = value;
            }
        }

        /// <remarks/>
        public string FunctionalState
        {
            get
            {
                return this.functionalStateField;
            }
            set
            {
                this.functionalStateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string HardwareIdentID
        {
            get
            {
                return this.hardwareIdentIDField;
            }
            set
            {
                this.hardwareIdentIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string FirmwareID
        {
            get
            {
                return this.firmwareIDField;
            }
            set
            {
                this.firmwareIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AttributeFile", IsNullable = false)]
        public System.Collections.Generic.List<AttributeFileAssignType> AttributeFiles
        {
            get
            {
                return this.attributeFilesField;
            }
            set
            {
                this.attributeFilesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("Count", IsNullable = false)]
        public System.Collections.Generic.List<byte> MacAddresses
        {
            get
            {
                return this.macAddressesField;
            }
            set
            {
                this.macAddressesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string InputImageByteCount
        {
            get
            {
                return this.inputImageByteCountField;
            }
            set
            {
                this.inputImageByteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string OutputImageByteCount
        {
            get
            {
                return this.outputImageByteCountField;
            }
            set
            {
                this.outputImageByteCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string PanelID
        {
            get
            {
                return this.panelIDField;
            }
            set
            {
                this.panelIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Board", IsNullable = false)]
        public System.Collections.Generic.List<BoardMountType> Boards
        {
            get
            {
                return this.boardsField;
            }
            set
            {
                this.boardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Module", IsNullable = false)]
        public System.Collections.Generic.List<ModuleMountType> Modules
        {
            get
            {
                return this.modulesField;
            }
            set
            {
                this.modulesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Connector", IsNullable = false)]
        public System.Collections.Generic.List<ConnectorMountType> Connectors
        {
            get
            {
                return this.connectorsField;
            }
            set
            {
                this.connectorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Wire", IsNullable = false)]
        public System.Collections.Generic.List<WireType> Wiring
        {
            get
            {
                return this.wiringField;
            }
            set
            {
                this.wiringField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class AttributeFileAssignType
    {

        private string attributeFileIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string AttributeFileID
        {
            get
            {
                return this.attributeFileIDField;
            }
            set
            {
                this.attributeFileIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class FirmwareVersionType
    {

        private byte majorField;

        private byte minorField;

        private byte releaseField;

        private byte buildField;

        private System.DateTime buildTimeField;

        /// <remarks/>
        public byte Major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }

        /// <remarks/>
        public byte Minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }

        /// <remarks/>
        public byte Release
        {
            get
            {
                return this.releaseField;
            }
            set
            {
                this.releaseField = value;
            }
        }

        /// <remarks/>
        public byte Build
        {
            get
            {
                return this.buildField;
            }
            set
            {
                this.buildField = value;
            }
        }

        /// <remarks/>
        public System.DateTime BuildTime
        {
            get
            {
                return this.buildTimeField;
            }
            set
            {
                this.buildTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class WireTerminalType
    {

        private System.Collections.Generic.List<string> itemsField;

        private System.Collections.Generic.List<ItemsChoiceType1> itemsElementNameField;

        private string pinNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoardReference", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ConnectorReference", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ModuleReference", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("SwitchReference", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public System.Collections.Generic.List<string> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<ItemsChoiceType1> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        public string PinName
        {
            get
            {
                return this.pinNameField;
            }
            set
            {
                this.pinNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP", IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        BoardReference,

        /// <remarks/>
        ConnectorReference,

        /// <remarks/>
        ModuleReference,

        /// <remarks/>
        SwitchReference,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class WireType
    {

        private WireTerminalType fromField;

        private WireTerminalType toField;

        /// <remarks/>
        public WireTerminalType From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        public WireTerminalType To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class OnBoardConnectionTerminalType
    {

        private string connectorReferenceField;

        private string pinNameField;

        /// <remarks/>
        public string ConnectorReference
        {
            get
            {
                return this.connectorReferenceField;
            }
            set
            {
                this.connectorReferenceField = value;
            }
        }

        /// <remarks/>
        public string PinName
        {
            get
            {
                return this.pinNameField;
            }
            set
            {
                this.pinNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class OnBoardConnectionType
    {

        private string nameField;

        private OnBoardConnectionTerminalType fromField;

        private object itemField;

        private ItemChoiceType itemElementNameField;

        private bool invertingField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public OnBoardConnectionTerminalType From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InputImageBit", typeof(ImageBitType))]
        [System.Xml.Serialization.XmlElementAttribute("OutputImageBit", typeof(ImageBitType))]
        [System.Xml.Serialization.XmlElementAttribute("To", typeof(OnBoardConnectionTerminalType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public bool Inverting
        {
            get
            {
                return this.invertingField;
            }
            set
            {
                this.invertingField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ImageBitType
    {

        private string byteField;

        private int bitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string Byte
        {
            get
            {
                return this.byteField;
            }
            set
            {
                this.byteField = value;
            }
        }

        /// <remarks/>
        public int Bit
        {
            get
            {
                return this.bitField;
            }
            set
            {
                this.bitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        InputImageBit,

        /// <remarks/>
        OutputImageBit,

        /// <remarks/>
        To,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabelMountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoardMountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectorMountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleMountType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchMountType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class MountType
    {

        private string referenceField;

        private PlacementType placementField;

        private ImageBitType inputImageOffsetField;

        private ImageBitType outputImageOffsetField;

        /// <remarks/>
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <remarks/>
        public PlacementType Placement
        {
            get
            {
                return this.placementField;
            }
            set
            {
                this.placementField = value;
            }
        }

        /// <remarks/>
        public ImageBitType InputImageOffset
        {
            get
            {
                return this.inputImageOffsetField;
            }
            set
            {
                this.inputImageOffsetField = value;
            }
        }

        /// <remarks/>
        public ImageBitType OutputImageOffset
        {
            get
            {
                return this.outputImageOffsetField;
            }
            set
            {
                this.outputImageOffsetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class PlacementType
    {

        private PointType positionField;

        private PointType axisField;

        private double angleField;

        /// <remarks/>
        public PointType Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        public PointType Axis
        {
            get
            {
                return this.axisField;
            }
            set
            {
                this.axisField = value;
            }
        }

        /// <remarks/>
        public double Angle
        {
            get
            {
                return this.angleField;
            }
            set
            {
                this.angleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class PointType
    {

        private double xField;

        private double yField;

        private double zField;

        /// <remarks/>
        public double X
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }

        /// <remarks/>
        public double Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }

        /// <remarks/>
        public double Z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class LabelMountType : MountType
    {

        private string labelIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string LabelID
        {
            get
            {
                return this.labelIDField;
            }
            set
            {
                this.labelIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class BoardMountType : MountType
    {

        private string boardIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string BoardID
        {
            get
            {
                return this.boardIDField;
            }
            set
            {
                this.boardIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ConnectorMountType : MountType
    {

        private string connectorIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string ConnectorID
        {
            get
            {
                return this.connectorIDField;
            }
            set
            {
                this.connectorIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ModuleMountType : MountType
    {

        private string switchReferencePrefixField;

        private string moduleIDField;

        /// <remarks/>
        public string SwitchReferencePrefix
        {
            get
            {
                return this.switchReferencePrefixField;
            }
            set
            {
                this.switchReferencePrefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string ModuleID
        {
            get
            {
                return this.moduleIDField;
            }
            set
            {
                this.moduleIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SwitchMountType : MountType
    {

        private string switchIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "IDREF")]
        public string SwitchID
        {
            get
            {
                return this.switchIDField;
            }
            set
            {
                this.switchIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SwitchPositionListType
    {

        private System.Collections.Generic.List<SwitchPositionType> positionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public System.Collections.Generic.List<SwitchPositionType> Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SwitchPositionType
    {

        private string nameField;

        private double angleField;

        private System.Collections.Generic.List<string> activeInputsField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public double Angle
        {
            get
            {
                return this.angleField;
            }
            set
            {
                this.angleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ListIndex", DataType = "nonNegativeInteger", IsNullable = false)]
        public System.Collections.Generic.List<string> ActiveInputs
        {
            get
            {
                return this.activeInputsField;
            }
            set
            {
                this.activeInputsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SignalListType
    {

        private System.Collections.Generic.List<SignalType> signalField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signal")]
        public System.Collections.Generic.List<SignalType> Signal
        {
            get
            {
                return this.signalField;
            }
            set
            {
                this.signalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SignalType
    {

        private string nameField;

        private System.Collections.Generic.List<object> itemsField;

        private System.Collections.Generic.List<ItemsChoiceType> itemsElementNameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ImageOffset", typeof(ImageBitType))]
        [System.Xml.Serialization.XmlElementAttribute("InPin", typeof(PinType))]
        [System.Xml.Serialization.XmlElementAttribute("OutPin", typeof(PinType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Collections.Generic.List<ItemsChoiceType> ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class PinType
    {

        private string nameField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        ImageOffset,

        /// <remarks/>
        InPin,

        /// <remarks/>
        OutPin,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FirmwareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SolidType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoardType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PanelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HardwareIdentType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ElementType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FirmwareType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SolidType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoardType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PanelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class PartType : ElementType
    {

        private string nameField;

        private string itemNumberField;

        private string revisionField;

        private string segmentField;

        private string instanceField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string ItemNumber
        {
            get
            {
                return this.itemNumberField;
            }
            set
            {
                this.itemNumberField = value;
            }
        }

        /// <remarks/>
        public string Revision
        {
            get
            {
                return this.revisionField;
            }
            set
            {
                this.revisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Segment
        {
            get
            {
                return this.segmentField;
            }
            set
            {
                this.segmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string Instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AttributeFileType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FirmwareType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class FileType : PartType
    {

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        private string targetFileNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Binary", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("SourceFileName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        public string TargetFileName
        {
            get
            {
                return this.targetFileNameField;
            }
            set
            {
                this.targetFileNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        Binary,

        /// <remarks/>
        SourceFileName,

        /// <remarks/>
        Text,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class AttributeFileType : FileType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class FirmwareType : FileType
    {

        private FirmwareVersionType versionField;

        /// <remarks/>
        public FirmwareVersionType Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LabelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoardType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PanelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModuleType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SwitchType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SolidType : PartType
    {

        private PointType dimensionField;

        private PlacementType placementField;

        /// <remarks/>
        public PointType Dimension
        {
            get
            {
                return this.dimensionField;
            }
            set
            {
                this.dimensionField = value;
            }
        }

        /// <remarks/>
        public PlacementType Placement
        {
            get
            {
                return this.placementField;
            }
            set
            {
                this.placementField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class LabelType : SolidType
    {

        private object itemField;

        private string colorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Picture", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("Text", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string Color
        {
            get
            {
                return this.colorField;
            }
            set
            {
                this.colorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ConnectorType : SolidType
    {

        private System.Collections.Generic.List<PinType> pinsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Pin", IsNullable = false)]
        public System.Collections.Generic.List<PinType> Pins
        {
            get
            {
                return this.pinsField;
            }
            set
            {
                this.pinsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class BoardType : SolidType
    {

        private string categoryField;

        private System.Collections.Generic.List<ConnectorMountType> connectorsField;

        private System.Collections.Generic.List<OnBoardConnectionType> connectionsField;

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Connector", IsNullable = false)]
        public System.Collections.Generic.List<ConnectorMountType> Connectors
        {
            get
            {
                return this.connectorsField;
            }
            set
            {
                this.connectorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Connection", IsNullable = false)]
        public System.Collections.Generic.List<OnBoardConnectionType> Connections
        {
            get
            {
                return this.connectionsField;
            }
            set
            {
                this.connectionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class PanelType : SolidType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class ModuleType : SolidType
    {

        private System.Collections.Generic.List<ModuleCategoryType> categoriesField;

        private System.Collections.Generic.List<SwitchMountType> switchesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable = false)]
        public System.Collections.Generic.List<ModuleCategoryType> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Switch", IsNullable = false)]
        public System.Collections.Generic.List<SwitchMountType> Switches
        {
            get
            {
                return this.switchesField;
            }
            set
            {
                this.switchesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public enum ModuleCategoryType
    {

        /// <remarks/>
        USB,

        /// <remarks/>
        COM,

        /// <remarks/>
        DIO,

        /// <remarks/>
        KBD,

        /// <remarks/>
        NUM,

        /// <remarks/>
        Mouse,

        /// <remarks/>
        MouseBtn,

        /// <remarks/>
        Track,

        /// <remarks/>
        Touch,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class SwitchType : SolidType
    {

        private SwitchCategoryType categoryField;

        private System.Collections.Generic.List<object> itemsField;

        private System.Collections.Generic.List<SignalType> outputsField;

        private LabelMountType labelField;

        /// <remarks/>
        public SwitchCategoryType Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Inputs", typeof(SignalListType))]
        [System.Xml.Serialization.XmlElementAttribute("KeyCode", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Positions", typeof(SwitchPositionListType))]
        public System.Collections.Generic.List<object> Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Signal", IsNullable = false)]
        public System.Collections.Generic.List<SignalType> Outputs
        {
            get
            {
                return this.outputsField;
            }
            set
            {
                this.outputsField = value;
            }
        }

        /// <remarks/>
        public LabelMountType Label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public enum SwitchCategoryType
    {

        /// <remarks/>
        Turn,

        /// <remarks/>
        Key,

        /// <remarks/>
        EmergencyStop,

        /// <remarks/>
        GrayCode,

        /// <remarks/>
        BinCode,

        /// <remarks/>
        Indicator,

        /// <remarks/>
        Vibrator,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://devices.wkc.siemens.de/MCP")]
    public partial class HardwareIdentType : ElementType
    {

        private byte categoryField;

        private byte architectureField;

        private byte majorField;

        private byte minorField;

        private string nameField;

        /// <remarks/>
        public byte Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public byte Architecture
        {
            get
            {
                return this.architectureField;
            }
            set
            {
                this.architectureField = value;
            }
        }

        /// <remarks/>
        public byte Major
        {
            get
            {
                return this.majorField;
            }
            set
            {
                this.majorField = value;
            }
        }

        /// <remarks/>
        public byte Minor
        {
            get
            {
                return this.minorField;
            }
            set
            {
                this.minorField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}