// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading.Tasks;
using SqlConsoleApp.SqlContext.Models;

namespace SqlConsoleApp.SqlContext.Data
{
    public partial class SqlContextProcedures
    {
        private readonly SqlContext _context;

        public SqlContextProcedures(SqlContext context)
        {
            _context = context;
        }

        public async Task<int> InsertUpdateDeletePresenceAbsence(string Json, OutputParameter<int> returnValue = null)
        {
            var parameterJson = new SqlParameter
            {
                ParameterName = "Json",
                Value = Json ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };

            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [app].[InsertUpdateDeletePresenceAbsence] @Json", parameterJson, parameterreturnValue);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
