// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PieceOfTime.SqlContext.Models
{
    public partial class CCalendarTable
    {
        public int Id { get; set; }
        public int? IdDayType { get; set; }
        public DateTime? Date { get; set; }
        public decimal Factor { get; set; }
        public string DayName { get; set; }
        public int? Week { get; set; }
        public int? Month { get; set; }
        public string MonthName { get; set; }
        public int? Year { get; set; }
        public int? IsoWeek { get; set; }
        public int? Quarter { get; set; }
        public int? DayOfWeek { get; set; }
        public int? DayOfMonth { get; set; }
        public int? DayOfYear { get; set; }
        public int? FiscalMonth { get; set; }
        public int? FiscalYear { get; set; }
    }
}