// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PieceOfTime.SqlContext.Models
{
    public partial class CCalendarTable
    {
        public int Id { get; }
        public int? IdDayType { get; }
        public DateTime? Date { get; }
        public decimal Factor { get; }
        public string DayName { get; }
        public int? Week { get; }
        public int? Month { get; }
        public string MonthName { get; }
        public int? Year { get; }
        public int? IsoWeek { get; }
        public int? Quarter { get; }
        public int? DayOfWeek { get; }
        public int? DayOfMonth { get; }
        public int? DayOfYear { get; }
        public int? FiscalMonth { get; }
        public int? FiscalYear { get; }
    }
}