// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PieceOfTime.SqlContext.Models
{
    public partial class DayTypes
    {
        public int Id { get; set; }
        public string DayType { get; set; }
    }
}