// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace PieceOfTime.SqlContext.Models
{
    public partial class PresenceAbsence
    {
        public int Id { get; set; }
        public int IdMitarbeiter { get; set; }
        public int IdOrganisation { get; set; }
        public int IdCalendarTable { get; set; }
        public int IdDayType { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
    }
}